var gr_tanks = {
        "name": "Tanks",
        "stands": [
			{"name": "Panzer I",   "class": "III",   "move": "24/12T ",   "def": "1/1S",   "year": "35",   "weapons": [{"name": "T:MG",   "ammoTypes": "3092"}]},
{"name": "Panzer I BfWg",   "class": "III",   "move": "24/12T ",   "def": "1/1S",   "year": "35",   "weapons": [{"name": "C:MG",   "ammoTypes": "3093"}]},
{"name": "Panzer II b",   "class": "III",   "move": "24/12T ",   "def": "2/1S",   "year": "35",   "weapons": [{"name": "T:20L55",   "ammoTypes": "3094"},{"name": "T:MG",   "ammoTypes": "3095"}]},
{"name": "Flamm Panzer II",   "class": "III",   "move": "24/12T ",   "def": "3/2S",   "year": "40",   "weapons": [{"name": "T:FT",   "ammoTypes": "3096"},{"name": "T:MG",   "ammoTypes": "3097"}]},
{"name": "Panzer II f",   "class": "III",   "move": "24/12T ",   "def": "3/2S",   "year": "41",   "weapons": [{"name": "T:20L55",   "ammoTypes": "3098"},{"name": "T:MG",   "ammoTypes": "3099"}]},
{"name": "Panzer II L \"Luchs\"",   "class": "IV",   "move": "36/16T ",   "def": "3/2S",   "year": "43",   "weapons": [{"name": "T:20L55",   "ammoTypes": "3100"},{"name": "T:MG",   "ammoTypes": "3101"}]},
{"name": "Flamm Panzer III",   "class": "V",   "move": "24/12T ",   "def": "9/3S",   "year": "43",   "weapons": [{"name": "T:FT",   "ammoTypes": "3102"},{"name": "T:MG",   "ammoTypes": "3103"}]},
{"name": "Panzer 35(t)",   "class": "IV",   "move": "22/10T ",   "def": "3/2S",   "year": "40",   "weapons": [{"name": "T:37L40",   "ammoTypes": "3104"},{"name": "T,H:MG",   "ammoTypes": "3105"}]},
{"name": "Panzer 38(t) a-d",   "class": "IV",   "move": "24/12T ",   "def": "3/2S",   "year": "39",   "weapons": [{"name": "T:37L49",   "ammoTypes": "3106"},{"name": "T,H:MG",   "ammoTypes": "3107"}]},
{"name": "Panzer 38(t) e/f",   "class": "IV",   "move": "24/12T ",   "def": "5/3S",   "year": "42",   "weapons": [{"name": "T:37L49",   "ammoTypes": "3108"},{"name": "T,H:MG",   "ammoTypes": "3109"}]},
{"name": "Flammpanzer 38(t) \"Hetzer\"",   "class": "IV",   "move": "24/12T ",   "def": "11/3S",   "year": "44",   "weapons": [{"name": "C:FT",   "ammoTypes": "3110"},{"name": "C:MG",   "ammoTypes": "3111"}]},
{"name": "Panzer III BfW",   "class": "IV",   "move": "24/12T ",   "def": "3/3S",   "year": "39",   "weapons": [{"name": "T:MG",   "ammoTypes": "3112"}]},
{"name": "Panzer III Beo",   "class": "IV",   "move": "24/12T ",   "def": "7/3S",   "year": "43",   "weapons": [{"name": "T:MG",   "ammoTypes": "3113"}]},
{"name": "Panzer III e",   "class": "IV",   "move": "24/12T ",   "def": "3/3S",   "year": "39",   "weapons": [{"name": "T:37L45",   "ammoTypes": "3114"},{"name": "T:MG",   "ammoTypes": "3115"},{"name": "H:MG",   "ammoTypes": "3116"}]},
{"name": "Panzer III Tauchpanzer",   "class": "IV",   "move": "24/12T ",   "def": "3/3S",   "year": "40",   "weapons": [{"name": "T:37L45",   "ammoTypes": "3117"},{"name": "T:MG",   "ammoTypes": "3118"},{"name": "H:MG",   "ammoTypes": "3119"}]},
{"name": "Panzer III f/g",   "class": "IV",   "move": "24/12T ",   "def": "4/3S",   "year": "41",   "weapons": [{"name": "T:50L42",   "ammoTypes": "3120"},{"name": "T:MG",   "ammoTypes": "3121"},{"name": "H:MG",   "ammoTypes": "3122"}]},
{"name": "Panzer III h",   "class": "IV",   "move": "24/12T ",   "def": "5/3S",   "year": "41",   "weapons": [{"name": "T:50L42",   "ammoTypes": "3123"},{"name": "T,H:MG",   "ammoTypes": "3124"}]},
{"name": "Panzer III j short ",   "class": "V",   "move": "24/12T ",   "def": "6/3S",   "year": "42",   "weapons": [{"name": "T:50L42",   "ammoTypes": "3125"},{"name": "T,H:MG",   "ammoTypes": "3126"}]},
{"name": "Panzer III j long",   "class": "V",   "move": "24/12T ",   "def": "6/3S",   "year": "42",   "weapons": [{"name": "T:50L60",   "ammoTypes": "3127"},{"name": "T,H:MG",   "ammoTypes": "3128"}]},
{"name": "Panzer III l/m",   "class": "V",   "move": "24/12T ",   "def": "8/3S",   "year": "42",   "weapons": [{"name": "T:50L60",   "ammoTypes": "3129"},{"name": "T,H:MG",   "ammoTypes": "3130"}]},
{"name": "Panzer III n",   "class": "V",   "move": "24/12T ",   "def": "6/3S",   "year": "42",   "weapons": [{"name": "T:75L24",   "ammoTypes": "3131"},{"name": "T,H:MG",   "ammoTypes": "3132"}]},
{"name": "Panzer IV d",   "class": "V",   "move": "24/12T ",   "def": "3/2S",   "year": "38",   "weapons": [{"name": "T:75L24",   "ammoTypes": "3133"},{"name": "T,H:MG",   "ammoTypes": "3134"}]},
{"name": "Panzer IV e",   "class": "IV",   "move": "24/12T ",   "def": "4/3S",   "year": "40",   "weapons": [{"name": "T:75L24",   "ammoTypes": "3135"},{"name": "T,H:MG",   "ammoTypes": "3136"}]},
{"name": "Panzer IV f-1",   "class": "V",   "move": "24/12T ",   "def": "5/3S",   "year": "41",   "weapons": [{"name": "T:75L24",   "ammoTypes": "3137"},{"name": "T,H:MG",   "ammoTypes": "3138"}]},
{"name": "Panzer IV f-2 & Panzer IVg (early)",   "class": "V",   "move": "24/12T ",   "def": "5/3S",   "year": "42",   "weapons": [{"name": "T:75L43",   "ammoTypes": "3139"},{"name": "T,H:MG",   "ammoTypes": "3140"}]},
{"name": "Panzer IV g (late) and Panzer IVh",   "class": "V",   "move": "24/12T ",   "def": "6/3S",   "year": "43",   "weapons": [{"name": "T:75L48",   "ammoTypes": "3141"},{"name": "T,H:MG",   "ammoTypes": "3142"}]},
{"name": "Panzer V d \"Panther\"",   "class": "VI",   "move": "28/16T ",   "def": "12/5S",   "year": "43",   "weapons": [{"name": "T:75L70",   "ammoTypes": "3143"},{"name": "T:MG",   "ammoTypes": "3144"}]},
{"name": "Panzer V g \"Panther\"",   "class": "VI",   "move": "28/16T ",   "def": "12/5S",   "year": "44",   "weapons": [{"name": "T:75L70",   "ammoTypes": "3145"},{"name": "T,TP,HMG",   "ammoTypes": "3146"}]},
{"name": "Beo Panther",   "class": "VI",   "move": "28/16T ",   "def": "12/5S",   "year": "43",   "weapons": [{"name": "T:MG",   "ammoTypes": "3147"}]},
{"name": "Panzer VI e \"Tiger\"",   "class": "VI",   "move": "22/12T ",   "def": "12/8S",   "year": "42",   "weapons": [{"name": "T:88L56",   "ammoTypes": "3148"},{"name": "T,H:MG",   "ammoTypes": "3149"}]},
{"name": "Panzer VI b \"King Tiger\"",   "class": "VI",   "move": "22/10T ",   "def": "15/9S",   "year": "44",   "weapons": [{"name": "T:88L71",   "ammoTypes": "3150"},{"name": "T,H:MG",   "ammoTypes": "3151"}]},
{"name": "Panzer \"Maus\"",   "class": "VII",   "move": "12/8T ",   "def": "20/14S",   "year": "45",   "weapons": [{"name": "T:128L55",   "ammoTypes": "3152"},{"name": "T:75L36",   "ammoTypes": "3153"},{"name": "T:MG",  
 "ammoTypes": "3154"}]}
		]
	   }; 
	   
	   console.log("tanks loaded");